pipelines:
  - name: basicq
    steps:
      - name: basic1
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo {{ .Values.foo.bar }}
      - name: basic2
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: basic1
        execution:
          onExecute:
            - echo {{ .Values.foo.baz }}
      - name: basic3
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: basic2
        execution:
          onExecute:
            - echo {{ .Values.foo.zoo }}



